language: ruby
sudo: false
rvm:
  - 2.4.2
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
before_install:
  - gem install bundler -v '<2.0'
cache: bundler
notifications:
  email: false
